name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set .bashrc path
        shell: pwsh
        run: echo "{BASHRC_PATH}=$Env:HOME/.bashrc"  >> $GITHUB_ENV
      - name: echo .bashrc path
        shell: pwsh
        run: echo "$env:BASHRC_PATH"
      - uses: DamianReeves/write-file-action@master
        with:
          path: ${{ env.BASHRC_PATH }}
          contents: |
            echo "Hello World!"
          write-mode: append
      - uses: actions/upload-artifact@v1
        with:
          name: profile
          path: ${{ env.BASHRC_PATH }}
